# based on https://github.com/hmcts/chart-java/blob/master/java/values.yaml
image:
  registry: hmctspublic.azurecr.io
  repository: imported/postgres
  tag: "17.6-alpine"
## Default Postgres Configuration parameters
auth:
  username: javapostgres
  password: javapassword

primary:
  ## Disable Postgres Persistence
  persistence:
    enabled: false
  ## extra volume mount for PostgreSQL writes socket lock file to /var/run/postgresql directory
  extraVolumes:
    - name: postgresql-run
      emptyDir: {}
    ## @param primary.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the PostgreSQL Primary container(s)
    ##
  extraVolumeMounts:
    - name: postgresql-run
      mountPath: /var/run/postgresql

global:
  enableKeyVaults: false
  devMode: false
